logging:
  config: classpath:log4j2.xml # 配置日志文件
server:
  port: 5001 # 服务器端口
  ssl:
    enabled: true # 开启 HTTPS 验证
    key-alias: 1
    key-store: classpath:my-game-web.p12 # 证书配置
    key-store-password: changeit # 证书密码
    key-store-type: PKCS12 # 证书类型
spring:
  application:
    name: game-web-gateway-server
  cloud:
    consul:
      host: 192.168.63.131 # Consul 地址，需要替换成自己的服务地址
      port: 8500 # Consul 端口
      discovery:
        prefer-ip-address: true # 默认向 Consul 服务中心注册的是当前主机的 hostname，这里选择使用 IP
        ip-address: 192.168.110.48 # 向 Consul 服务中心注册的 IP
        register: false # 因为只有网关会转发到其他服务，所以这里关闭网关向 consul 注册
        scheme: https # 注册 scheme，这样 consul 会以 https 的方式访问网关服务
    gateway:
      discovery:
        locator:
######################################### 手动配置 ###########################################
          enabled: false # 关闭自动路由配置
      routes: # 手动配置路由信息
      - id: game-center-server
        uri: lb://game-center-server   # 配置服务id
        predicates:
        - name: Path
          args:
            pattern: /game-center-server/** # 匹配的 URL 模式，URL 的路径必须以 game-center-server 开发，包括它所有的子路径
        filters:
        - name: RewritePath
          args:
            regexp: /game-center-server/(?<remaining>.*)
            replacement: /${remaining}
################################# 与 Consul组合自动配置路由信息 #################################
#          enabled: true # 开启与服务发现组件结合，通过 serviceId 转发到具体的服务
management:
  endpoints:
    web:
      exposure:
        include: '*' # 可从 Consul 中获取所有注册成功的服务信息，并自动生成每个服务匹配的路径信息

gateway:
  filter:
    white-request-uri:
    - /request/10001 # 登录请求的URL
    - /test/https
    user-request-rate-count: 3
    global-request-rate-count: 3000
    cache-user-max-count: 5000
    cache-user-timeout: 30000