logging:
  config: classpath:log4j2.xml
server:
  port: 6002
spring:
  application:
    name: game-gateway-001
  cloud:
    consul:
      host: 192.168.63.131
      port: 8500
      discovery:
        prefer-ip-address: true
        ip-address: 192.168.110.48
        register: true # 将游戏服务网关作为服务节点，注册到 Consul 上面
        service-name: game-gateway # 注册到 Consul 上面的服务名称，用于区分此服务是否为游戏服务器网关
        health-check-critical-timeout: 30s
        metadata:
          gamePort: ${game.gateway.server.config.port} # 自定义数据，游戏服务器网关的长连接端口
          weight: 3 # 游戏服务器网关权重
    bus:
      enabled: true # 开启消息总线服务
    stream:
      kafka:
        binder:
          brokers: 192.168.63.131:9092 # 配置 Kafka 地址
  kafka:
    producer:
      bootstrap-servers: 192.168.63.131:9092
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer  # 指定生产者的Key的序列化方式
    bootstrap-servers: 192.168.63.131:9092



game:
  gateway:
    server:
      config:
        port: 6003 # 游戏服务器网关的长连接端口，这里的数据是自定义配置
        boss-thread-count: 1
        work-thread-count: 4
