logging:
  # SpringBoot - 配置文件application.yml使用详解（附：Profile多环境配置） https://www.hangge.com/blog/cache/detail_2459.html
  config: classpath:log4j2.xml # 配置日志文件
server:
  port: 5002 # or 5003 # 服务器端口
spring:
  application:
    name: game-center-server
  data:
    mongodb:
      host: 192.168.63.131 # 修改为自己的数据库地址
      port: 27017
      username: my-game # 修改为自己的数据库用户名
      password: xxx123456 # 修改为自己的数据库密码
      authentication-database: admin
      database: my-game
  redis:
    host: 192.168.63.131 # 修改为自己的 Redis 服务地址
    port: 6379
    password: R6YMtyPGS0f968IM
    database: 10
  cloud:
    consul:
      host: 192.168.63.131 # Consul 服务的地址
      port: 8500 # Consul 服务的端口
      discovery:
        prefer-ip-address: true # IP 地址注册优先
        ip-address: 192.168.110.48 # 要注册的服务IP
    bus:
      enabled: false